#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: cf1/cf1
        child_frame_id: vicon/cf1/cf1
        parent_frame_id: /world
    '2':
        pose: cf2/cf2
        child_frame_id: vicon/cf2/cf2
        parent_frame_id: /world
    '3':
        pose: cf3/cf3
        child_frame_id: vicon/cf3/cf3
        parent_frame_id: /world
    '4':
        pose: cf4/cf4
        child_frame_id: vicon/cf4/cf4
        parent_frame_id: /world
    '5':
        pose: cf5/cf5
        child_frame_id: vicon/cf5/cf5
        parent_frame_id: /world
optitrack_config:
        multicast_address: 239.255.42.99
        command_port: 1510
        data_port: 1511
